[workspace]
resolver = "2"
members = ["trame", "trame-runtime"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/facet-rs/trame"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)', 'cfg(creusot)'] }

[workspace.dependencies]
facet-core = { git = "https://github.com/facet-rs/facet", branch = "main" }
facet = { git = "https://github.com/facet-rs/facet", branch = "main" }
bitflags = "2.10.0"
smallvec = "2.0.0-alpha.12"
